// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Replace with your actual Supabase URL and anon key
const SUPABASE_URL = "YOUR_SUPABASE_URL_HERE";
const SUPABASE_PUBLISHABLE_KEY = "YOUR_SUPABASE_ANON_KEY_HERE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});