// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/list-consents.ts
import { createClient } from "npm:@supabase/supabase-js@^2.53.0";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^3.25.76";
function supabaseForUser(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_consents_default = defineTool({
  name: "list_consents",
  title: "List consents",
  description: "List informed-consent records visible to the signed-in user, with optional filters by status, source, consent type, patient name or document number.",
  inputSchema: {
    status: z.enum(["pending", "sent", "signed", "expired", "cancelled"]).optional(),
    source: z.enum(["web", "app"]).optional(),
    consent_type: z.string().optional().describe("Consent type key (e.g. carga_glucosa, hiv)."),
    patient_name: z.string().optional().describe("Case-insensitive partial match on patient name."),
    patient_document_number: z.string().optional(),
    limit: z.number().int().min(1).max(100).optional().describe("Max rows to return (default 25).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("consents").select(
      "id, created_at, patient_name, patient_document_type, patient_document_number, consent_type, status, signed_at, source"
    ).order("created_at", { ascending: false }).limit(input.limit ?? 25);
    if (input.status) query = query.eq("status", input.status);
    if (input.source) query = query.eq("source", input.source);
    if (input.consent_type) query = query.eq("consent_type", input.consent_type);
    if (input.patient_document_number)
      query = query.eq("patient_document_number", input.patient_document_number);
    if (input.patient_name) query = query.ilike("patient_name", `%${input.patient_name}%`);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { count: data?.length ?? 0, items: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-consent.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.53.0";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z2 } from "npm:zod@^3.25.76";
function supabaseForUser2(ctx) {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var get_consent_default = defineTool2({
  name: "get_consent",
  title: "Get consent",
  description: "Fetch full details of a single informed-consent record by id.",
  inputSchema: { id: z2.string().uuid().describe("Consent row id (uuid).") },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ id }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { data, error } = await supabaseForUser2(ctx).from("consents").select("*").eq("id", id).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data) return { content: [{ type: "text", text: "Consent not found" }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { consent: data }
    };
  }
});

// src/lib/mcp/tools/consent-stats.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.53.0";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z3 } from "npm:zod@^3.25.76";
function supabaseForUser3(ctx) {
  return createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var consent_stats_default = defineTool3({
  name: "consent_stats",
  title: "Consent statistics",
  description: "Return counts of informed-consent records visible to the signed-in user, grouped by status (and optionally within a date range).",
  inputSchema: {
    from: z3.string().optional().describe("ISO date lower bound on created_at."),
    to: z3.string().optional().describe("ISO date upper bound on created_at.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ from, to }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser3(ctx);
    let query = supabase.from("consents").select("status");
    if (from) query = query.gte("created_at", from);
    if (to) query = query.lte("created_at", to);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const counts = {};
    for (const row of data ?? []) {
      const s = row.status ?? "unknown";
      counts[s] = (counts[s] ?? 0) + 1;
    }
    const total = data?.length ?? 0;
    return {
      content: [{ type: "text", text: JSON.stringify({ total, by_status: counts }) }],
      structuredContent: { total, by_status: counts }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "dbhamokkweyadibngphq";
var mcp_default = defineMcp({
  name: "hplad-consent-mcp",
  title: "HPLAD Consentimientos MCP",
  version: "0.1.0",
  instructions: "Tools to query informed-consent records for the E.S.E. Hospital Pedro Le\xF3n \xC1lvarez D\xEDaz. Use `list_consents` to search, `get_consent` for one record, and `consent_stats` for counts by status. All data is scoped to the signed-in user via Supabase RLS.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_consents_default, get_consent_default, consent_stats_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
